FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json ./
COPY apps apps
COPY packages packages
COPY tsconfig.base.json .
RUN npm install && npm run build --workspace @streamforge/frontend && npm run build --workspace @streamforge/admin

FROM nginx:1.27-alpine
COPY infrastructure/nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/apps/frontend/dist /usr/share/nginx/html
COPY --from=build /app/apps/admin/dist /usr/share/nginx/html/admin
